#ifndef CONFIG_H
#define CONFIG_H

#define MRASTER_PROJECT_NAME  "@CMAKE_PROJECT_NAME@"

#define MRASTER_VERSION       "@MRaster_VERSION@"
#define MRASTER_VERSION_MAJOR @MRaster_VERSION_MAJOR@
#define MRASTER_VERSION_MINOR @MRaster_VERSION_MINOR@
#define MRASTER_VERSION_PATCH @MRaster_VERSION_PATCH@
#define MRASTER_VERSION_TWEAK @MRaster_VERSION_TWEAK@
#define MRASTER_VERSION_TAG   "v@MRaster_VERSION@"
#define MRASTER_VERSION_DATE  "@MRASTER_VERSION_DATE@"

#define MRASTER_FOUND_DOXYGEN @MRASTER_FOUND_DOXYGEN@
#define MRASTER_FOUND_TIFF    @MRASTER_FOUND_TIFF@
#define MRASTER_FOUND_OPENGL  @MRASTER_FOUND_OPENGL@
#define MRASTER_FOUND_GLUT    @MRASTER_FOUND_GLUT@
#define MRASTER_FOUND_OPENMP  @MRASTER_FOUND_OPENMP@
#define MRASTER_FOUND_SDL2    @MRASTER_FOUND_SDL2@
#define MRASTER_FOUND_BTEST   @MRASTER_FOUND_BTEST@

#define MRASTER_OPT_128_INT @MRASTER_OPT_128_INT@
#define MRASTER_OPT_BTEST   @MRASTER_OPT_BTEST@
#define MRASTER_OPT_DOXYGEN @MRASTER_OPT_DOXYGEN@
#define MRASTER_OPT_OPENGL  @MRASTER_OPT_OPENGL@
#define MRASTER_OPT_OPENMP  @MRASTER_OPT_OPENMP@
#define MRASTER_OPT_SDL2    @MRASTER_OPT_SDL2@
#define MRASTER_OPT_TIFF    @MRASTER_OPT_TIFF@

#endif
