# -*- Mode:Org; Coding:utf-8; fill-column:158 -*-
# ######################################################################################################################################################.H.S.##
# FILE:        ColorSchemes.org
#+TITLE:       Color Schemes
#+AUTHOR:      Mitch Richling
#+EMAIL:       http://www.mitchr.me/
#+DATE:        2022-07-31
#+DESCRIPTION: DESCRIPTION FIXME
#+KEYWORDS:    KEYWORDS FIXME
#+LANGUAGE:    en
#+OPTIONS:     num:t toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t skip:nil d:nil todo:t pri:nil H:5 p:t author:t html-scripts:nil 
#+SEQ_TODO:    TODO:NEW(t)                         TODO:WORK(w)    TODO:HOLD(h)    | TODO:FUTURE(f)   TODO:DONE(d)    TODO:CANCELED(c)
#+PROPERTY: header-args :eval never-export
#+HTML_HEAD: <style>body { width: 95%; margin: 2% auto; font-size: 18px; line-height: 1.4em; font-family: Georgia, serif; color: black; background-color: white; }</style>
#+HTML_HEAD: <style>body { min-width: 500px; max-width: 1024px; }</style>
#+HTML_HEAD: <style>h1,h2,h3,h4,h5,h6 { color: #A5573E; line-height: 1em; font-family: Helvetica, sans-serif; }</style>
#+HTML_HEAD: <style>h1,h2,h3 { line-height: 1.4em; }</style>
#+HTML_HEAD: <style>h1.title { font-size: 3em; }</style>
#+HTML_HEAD: <style>.subtitle { font-size: 0.6em; }</style>
#+HTML_HEAD: <style>h4,h5,h6 { font-size: 1em; }</style>
#+HTML_HEAD: <style>.org-src-container { border: 1px solid #ccc; box-shadow: 3px 3px 3px #eee; font-family: Lucida Console, monospace; font-size: 80%; margin: 0px; padding: 0px 0px; position: relative; }</style>
#+HTML_HEAD: <style>.org-src-container>pre { line-height: 1.2em; padding-top: 1.5em; margin: 0.5em; background-color: #404040; color: white; overflow: auto; }</style>
#+HTML_HEAD: <style>.org-src-container>pre:before { display: block; position: absolute; background-color: #b3b3b3; top: 0; right: 0; padding: 0 0.2em 0 0.4em; border-bottom-left-radius: 8px; border: 0; color: white; font-size: 100%; font-family: Helvetica, sans-serif;}</style>
#+HTML_HEAD: <style>pre.example { white-space: pre-wrap; white-space: -moz-pre-wrap; white-space: -o-pre-wrap; font-family: Lucida Console, monospace; font-size: 80%; background: #404040; color: white; display: block; padding: 0em; border: 2px solid black; }</style>
#+HTML_LINK_HOME: https://www.mitchr.me/
#+HTML_LINK_UP: https://www.mitchr.me/FIXME
# ######################################################################################################################################################.H.E.##

#+ATTR_HTML: :border 2 solid #ccc :frame hsides :align center
|          <r> | <l>                                          |
|    *Author:* | /{{{author}}}/                               |
|   *Updated:* | /{{{modification-time(%Y-%m-%d %H:%M:%S)}}}/ |
| *Generated:* | /{{{time(%Y-%m-%d %H:%M:%S)}}}/              |
#+ATTR_HTML: :align center
Copyright \copy {{{time(%Y)}}} Mitch Richling. All rights reserved.

#+TOC: headlines 5

#        #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #
#        #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #
#   010  #    020  #    030  #    040  #    050  #    060  #    070  #    080  #    090  #    100  #    110  #    120  #    130  #    140  #    150  #    160  #    170  #    180  #    190  #    200  #    210  #    220  #    230  #    240  #    250  #    260  #    270  #    280  #    290  #
# 345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#        #         #         #         #         #         #         #         #         #         #         #         #         #         #         #       | #         #         #         #         #         #         #         #         #         #         #         #         #         #
#        #         #         #         #         #         #         #         #         #         #         #         #         #         #         #       | #         #         #         #         #         #         #         #         #         #         #         #         #         #

# To get org to evaluate all code blocks on export, add the following to the Emacs header on the first line of this file:
#     org-export-babel-evaluate:t; org-confirm-babel-evaluate:nil
#
# C-c C-x C-v (org-toggle-inline-images)
#

* Introduction
:PROPERTIES:
:CUSTOM_ID: introduction
:END:

*=MRaster=* provides access to a rich collection of color schemes.  Color schemes are exposed in the API as inner classes of the =colorTpl= class.  These
inner classes follow a regular naming convention:

  - =csCB ..........= RGB Color Brewer 2 (template: =csCB_tpl=
  - =csFPwebSafe ...= RGB Web safe colors (template: =csFP_tpl=
  - =csCCdiag ......= RGB color cube: diagonal gradients (template: =csCC_tpl=)
  - =csCCcons ......= RGB color cube: Gradients with constant brightness (template: =csCC_tpl=)
  - =csCColde ......= RGB color cube: Some classic color gradients (template: =csCC_tpl=)
  - =csCCud ........= RGB color cube: Two color up-down ramps (template: =csCC_tpl=)
  - =csCCSum .......= RGB color cube: Sum ramp (template: =csCC_tpl=)
  - =csHSLh ........= RGB color cube: Gradients starting at the center of the cube and extending to a corner
  - =csBin .........= RGB Binary Schemes (template: =csCC_tpl=)
  - =csPGrey .......= RGB Pseudo-greyscale
  - =csRainbow .....= RGB spectrum based colors

These classes are static in nature, and an instance is not required to use them.  They all have a member named "=c=" which is used to set the components of a
=colorTpl= instance passed as argument, or as a factory for =colorTpl= instances.

When used as a factory, color scheme classes return fully constructed  =colorTpl=  objects:

#+begin_src c++
mjr:color3c8b aColor = mjr::color3c8b::webSafeNormalVision.c(25);
#+end_src

Alternately, color scheme classes may set the components of a passed  =colorTpl=  instance:

#+begin_src c++
mjr::color3c8b aColor;
mjr::color3c8b::webSafeNormalVision.c(aColor, 25);
#+end_src

Color scheme classes may also be used by =colorTpl= methods to identify a color scheme.  For example, the =csSet= method can set the current object's
components based on a color scheme like so:

#+begin_src c++
mjr::color3c8b aColor;
aColor.csSet<mjr::color3c8b::webSafeNormalVision>(25);
#+end_src

** Color Scheme Class Interface

Not all color scheme classes have the same interface; however, the interfaces are uniformly designed:
  - *=numC=:* The number of colors available in the scheme 
    - Color schemes with a fixed number of colors at compile time have member =numC=
    - Color schemes with the number of colors set at run time, will have a =numC= argument for the =c= methods.
      - These schemes have two members specifying the range for =numC=: =minNumC= & =maxNumC=.
  - *=c=:* methods are used to set colors
    - All color schemes have a =colorTpl= factory methodand a =colorTpl= setter method taking a =colorTpl= instance as the first argument with the remaining arguments identical to the factory method.
    - The arguments for the =c= method vary according to the needs of the scheme.  For example:
      - =csCB*= color schemes take an =Nc= argument followed by a =csIdx=.
      - =csCC*= color schemes take a =csIdx= -- the =Nc= value being fixed at compile time.
      - The =csIdx= argument may be one of several types depending on the scheme:
        - *=csIntType=:* An integer type used to to select colors from discrete schemes (like Colorbrewer schemes).  When =clrChanT= is integral, gradient schemes can be considerd discrete as well.
        - *=csFltType=:* An floating point type used to select colors from continuous schemes (like gradiants).
        - *=csNatType=:* This will be =csIntType= when  =clrChanT= is integral, and =csFltType= otherwise.  It is used by =csHSLh*= schemes.

Many color schemes provide a number of colors that is a function of =chanStepMax=, which is directly related to the value of =clrChanT=.  For integral
=clrChanT= types, =chanStepMax= will be equal to =maxChanVal=. For floating point =clrChanT= types, =chanStepMax= will be equal to $2^32$.

* Color Cube Edge/Diagonal Graph Color Schemes

 The RGB color cube:

#+begin_src text
.                                                       _________________________
.                                                green / _____________________  /| yellow
.                                                     / / ___________________/ / |
.                                                    / / /| |               / /  |
.                                                   / / / | |              / / . |
.                                                  / / /| | |             / / /| |
.                                                 / / / | | |            / / / | |
.                                                / / /  | | |     white / / /| | |
.                                               / /_/__________________/ / / | | |
.                                              /________________________/ /  | | |
.                                         cyan | ______________________ | |  | | |
.                                              | | |    | | |_________| | |__| | |
.                                              | | |    | |___________| | |____| |
.                                              | | |   / / ___________| | |_  / / red
.                                              | | |  / / /           | | |/ / /
.                                              | | | / / /  black     | | | / /
.                                              | | |/ / /             | | |/ /
.                                              | | | / /              | | ' /
.                                              | | |/_/_______________| |  /
.                                              | |____________________| | /
.                                         blue |________________________|/ magenta
.                           
.                                       Vertexes and Center of the RGB Color Cube:
.                                       Name     R     G     B     Abriv
.                                       black    0.0   0.0   0.0   0
.                                       blue     0.0   0.0   1.0   b
.                                       green    0.0   1.0   0.0   g
.                                       red      1.0   0.0   0.0   r
.                                       yellow   1.0   1.0   0.0   y
.                                       cyan     0.0   1.0   1.0   c
.                                       magenta  1.0   0.0   1.0   m
.                                       white    1.0   1.0   1.0   w
.                                       grey50   0.5   0.5   0.5   h
#+end_src

 The edges of the cube taken with the corners as vertexes form a graph (referred to as "the cube edge graph" in this documentation).  Every trail (a walk with
 unique edges) with $n$ edges generates a color scheme with $\mathrm{maxChanVal}\cdot n - 1$ unique colors.  To make this scheme unique, we define the tree to
 have one of its end points the "start" of the scheme -- so we can map the integers from $[0,\mathrm{maxChanVal}\cdot n]$ to unique colors.

 Example:

#+BEGIN_QUOTE
    ="BCG"= defines a trail starting at =B= (blue), moving to =C= (cyan) next, and ending at =G= (green).  The color scheme has $0$ mapped to blue (the first
    vertex), $256$ mapped to cyan (the second vertex), and $511$ mapped to green (the final vertex).  For values between two vertex points, we linearly
    interpolate between the two values.
#+END_QUOTE

 If we expand the graph to also include edges between the diagonal points of each face (cyan to yellow for example), we have a larger graph with more options.
 This graph is referred to as "the face edge/diagonal graph" in this documentation.

 Color schemes defined in this way have several advantages, but they can be misleading because our perception of color change is non-linear in the RGB cube.
 We illustrate several useful and/or commonly used face edge/diagonal graph color schemes.

 Lastly, we can expand that graph by adding one vertex, called =h=, at the center of the cube with edges extending to each corner.  This graph is referred to
 as "complete cube graph with center" in this documentation.

** The Color Cube Rainbow

 This is one of the most commonly seen color schemes in scientific visualization, and it is also one of the worst because it can be misleading when
 mapped to linear values.

 The color cube rainbow map is generated by the unique six segment (6 vertex) cycle in the face edge graph not involving white or black:

  - =RYGCBMR= -- =csCColdeRainbow=

 If we expand to the edge face/diagonal graph, then we have may more six segment cycles not involving white or black:

  - =RBCGYMR=
  - =RBCMYGR=
  - =RBGCMYR=
  - =RBGCYMR=
  - =RBGYCMR=
  - =RBMCGYR=
  - =RBMCYGR=
  - =RBMYCGR=
  - =RGBCMYR=
  - =RGBCYMR=
  - =RGBMCYR=
  - =RGCBMYR=
  - =RGYCBMR=
  - =RMBGCYR=
  - =RMCBGYR=

** Hitting all the corners

  A common request is for a cycle in the face edge graph that uses every corner color of the RGB cube.  Not only do we have one, but 6 uniquely
  different ones -- not counting rearrangements or reversals:

   - =0BCGYWMR0=
   - =0BCWMRYG0=
   - =0BMRYWCG0=
   - =0BMWCGYR0=
   - =0GCBMWYR0=
   - =0GYWCBMR0=

  Another common request is for trees (so no color is used twice) starting at black and ending at white.  Several trees exist of lengths of 7 and 5:

   - =0BCGYRMW=
   - =0BMRYGCW=
   - =0GCBMRYW=
   - =0GYRMBCW=
   - =0RMBCGYW=
   - =0RYGCBMW=
   - =0BCGYW=
   - =0BMRYW=
   - =0GCBMW=
   - =0GYRMW=
   - =0RMBCW=
   - =0RYGCW=

  The three segment trees from black to white are useful in that the intensity (sum of the components) is a monotone increasing function from zero up to
  three.  One of them (0RYW) is often called the "fire ramp" as it ranges from black (flame base), up to yellow, then red, and finally to white hot.

   - =0BCW= -- =csCCsumBGR=
   - =0BMW= -- =csCCsumBRG=
   - =0GCW= -- =csCCsumGBR=
   - =0GYW= -- =csCCsumGRB=
   - =0RMW= -- =csCCsumRBG=
   - =0RYW= -- =csCCsumRGB= and =csCColdeFireRamp=

  Luminance based color schemes from the HSL color space are quite popular.  Some HSL schemes don't suffer from the perceptional non-linearity that some
  popular RGB schemes suffer from. What most people don't realize is that many of the most popular luminance based color schemes in the HSL color space are
  actually edge graphs in the RGB color cube!  It is also true that the most common "bad" color scheme in the RGB cube (the colorCubeRainbow), is an edge
  graph in the HSL hexcone!  In the end, the thing to remember is that both color spaces have both good and bad color schemes.  Of particular note, are the
  two segment trees from black to white in the RGB edge/diagonal graph -- they are the same as the two segment graphs in the edges of the HSL hexcone from
  black to white!

   - =0RW= -- H=0   red edge of the HSL hexcone
   - =0YW= -- H=60  yellow edge of the HSL hexcone
   - =0GW= -- H=120 green edge of the HSL hexcone
   - =0CW= -- H=180 cyan edge of the HSL hexcone
   - =0BW= -- H=240 blue edge of the HSL hexcone
   - =0MW= -- H=300 magenta edge of the HSL hexcone

** Hot Too Cold

 A very common color map used to map data with ranges from cold up to hot is known as the "cold too hot ramp".  This ramp provides colors from blue, up
 through green, and ends in red. It suffers from the same defects as the color cube rainbow; however, its use is so common that special support is provided
 via a named method.

  - "BCGYR" -- =csCColdeColdToHot=

 The traditional cold to hot ramp can be improved -- this is my personal opinion.  This new ramp still has the same problems the color cube rainbow has;
 however, it is more attractive.  This one moves from white (ice), up to water (blue), and then up to red (hot) via yellow.

  - =WCBYR= -- =csCColdeIceToWaterToHot=

** Constant Intensity Cycles

 Two cycles, with three edges each, exhibiting constant intensity for every color in the color scheme are genuinely useful.  They have the advantage that they
 always render a "bright" color.  The lower intensity version is best for projected media that don't do well with yellow.

  - =CMY= -- =csCCconsTwo= -- intensity == 2
  - =BRG= -- =csCCconsOne= -- intensity == 1

** One Segment Diverging Maps

 One edge trees in the face diagonal graph with a nearly constant intensity of 2 along the entire edge are useful for "diverging" or "bipolar" color
 schemes.  By definition, such color schemes will never involve black or white.

 While rarely used, the following maps are useful and suggested.  None of them have the problems associated with the color cube rainbow.

  - =YC= -- =csCCudBr=
  - =YM= -- =csCCudBg=
  - =MC= -- =csCCudGr=
  - =MY= -- =csCCudGb=
  - =CM= -- =csCCudRg=
  - =CY= -- =csCCudRb=

 The naming convention for the methods is not obvious.  Take, for example, setRGBcmpUpDownRampBr.  This is so named because of the computational algorithm
 used to compute the scheme: Blue up, red down, green constant (maxChanVal).

** Three Segment Diverging Maps

 Some three edge trees utilizing very different colors for starting and terminal points can form very nice "divergent" color maps.  Such maps can
 successfully illustrate variables with both positive and negative values or two mutually exclusive, opposing variables.  Only two are directly
 supported via named methods (selected for attractiveness):

  - =BWR= -- intensity between 1 and 3
  - =CWM= -- intensity between 2 and 3

** Center point ramps (HSL schemes)

 Color schemes from the HSL color space are popular because they are perceptually more linear.  The most popular maps extend from the center of HSL space,
 (0.0, 0.5, 0), to one of the primary color vertexes --- which have the same colors as the vertexes of the RGB cube excluding black and white.  These
 sequences are identical to ones from the center of RGB space, (0.5, 0.5, 0.5), to one of the vertexes excluding black and white!  So we can implement these
 color schemes directly in RGB color space much as we have the cube schemes above.

 Recall that we call the vertex at the center of the cube "=H=" -- for "Half way between everything". Using this new vertex, we have the following saturation
 based color schemes:

  - =HR= -- =csHSLhR=
  - =HG= -- =csHSLhG=
  - =HB= -- =csHSLhB=
  - =HC= -- =csHSLhC=
  - =HY= -- =csHSLhY=
  - =HM= -- =csHSLhM=

 The traversal from black to white -- through the center point -- is directly supported via a named method.  Note that cmpRGBcornerGradiant() supports this via
 a graph string of "0W".

  - =0W= -- =csCCdiag01=

 The other diagonal traversals (diagonal meaning through the center of the cube) are essentially two of the HSL saturation based schemes placed back to back.
 They can form effective divergent color schemes.  Black to white is technically one of them, but we have already covered that one.  Note that the
 cmpRGBcornerGradiant() function will support this class of schemes with a two element graph -- the first vertex and the last. The remaining three diagonal schemes
 are as follows:

  - =CR= -- =csCCdiagCR=
  - =MG= -- =csCCdiagMG=
  - =YB= -- =csCCdiagYB=

